### ISSUE TITLE
I tried to use en-CELEX.dict and it return unknown phone 'd'

### ISSUE THREAD

**Issue by halink0803** [prosodylab/prosodylab.dictionaries#1]

**Comment by kylebgorman** [comment]
Hi, I need more details if you'd like me to look into this. Could you provide a _minimal_ reproducible example with the commands you issued and the data you used?

**Comment by halink0803** [comment]
I have cloned and followed the instruction from here : [https://github.com/prosodylab/Prosodylab-Aligner](https://github.com/prosodylab/Prosodylab-Aligner), however there are some word like "WHO'S" or "HE'S" do not exist in the eng.dict dictionary so I try to use en-CELEX.dict which contain those words by clone this repository and run **"python3 -m aligner -a /data -d en-CELEX"** and it returned error **"Unknown phone 'd' in dictionary 'en-CELEX.dict' (ln. 1)."**

I have searched for example of training data or run a new dictionary but I cannot find it :( I am really appreciate if you can tell me how or show me some references or examples

**Comment by kylebgorman** [comment]
The Saxon genitive "posessive" apostrophe-s can attach to literally any
word in English so long as that word can be the end of a nominal clause:
1. Fred's opinion on ...
2. Every linguist I know's opinion on ...
3. That guy I was telling you about's opinion on ...

etc.

So to get full coverage you'd have to double the size of your dictionary.
Instead we just tokenize the 'S as a separate word. So you'd transcribe #1
as: FRED 'S OPINION ON ... That should work with the default dictionary.

If you still want to use CELEX, you'll need to change the phone set in the
YAML configuration file (en.yaml) to match the CELEX set. You can do this
quickly by just writing a script to enumerate the unique phone symbols in
en-CELEX.dict and dropping that in to the "phoneset" attribute. Then you
should be good to go.

FWIW: In my personal opinion, the CELEX dictionary is of very poor quality.
It contains at least as much bizarre lexical material as does the CMU
dictionary (the source for en.dict), but the transcriptions are
considerably more irregular and the overall coverage is much poorer.
Finally it uses the phonemic categories of Received Pronunciation, which
are a poor fit to any North American English variant---if that's what
you're working on. (YMMV if you're working on British English though.)

K

**Comment by halink0803** [comment]
@kylebgorman Oh, thank you so so much for your very detail answer, I would try to use your first recommendation to separate 'S as a word. It should work correctly, one more problem I would ask you for recommendation is that the personal name which might appear in the sound file and also do not exist in the dictionary file that cause error. My solution is manually adding that name to the dictionary file. Is there any ways to do that automatically?

**Comment by kylebgorman** [comment]
If you'd rather not enter the names yourself, you could try using a
machine-learning based grapheme-to-phoneme converter to fill in the missing
entries. A well-designed, well-studied, fast one is Sequitur (
https://www-i6.informatik.rwth-aachen.de/web/Software/g2p.html).

The problem is "ill-posed" (we know English has many homonyms that are not
homophones), so even the best system is going to make occasional errors,
though it may not matter for your ultimate  goals.

If you're working with English, it's difficult to do that with a simple
rule-based system---maybe easier in, say, Finnish.

**Comment by halink0803** [comment]
Thank you very much for your very helpful answer!
